# Generated by Django 5.1.7 on 2025-03-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_oauth_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
