# Generated by Django 5.1.5 on 2025-03-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_google_oauth_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmissioncomment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.assignmentsubmission'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmissionfile',
            name='content',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmissionfile',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assignmentsubmissionfile',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.assignmentsubmission'),
        ),
    ]
